config/urls.py
from django.contrib import admin
from django.urls import path, include  # we need to include urls in other app.
from django.conf import settings  # set 'from root' clearly
from django.conf.urls.static import static  # static() : help to serve static files


# we don't want our urls.py file make bigger.
# we need to 'divide and conquer' it in each app. folder.
urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("rooms/", include("rooms.urls", namespace="rooms")),
    path("users/", include("users.urls", namespace="users")),
    path("admin/", admin.site.urls),
]

if settings.DEBUG:  # Developement mode : serve files in my folder
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from rooms import views as room_views

app_name = "core"  # we can find core urls by using 'namespace' in config urls.

# urls for home etc.
urlpatterns = [
    path("", room_views.HomeView.as_view(), name="home"),  # name is url's name.
]

rooms/urls.py
from django.urls import path
from . import views

app_name = "rooms"

urlpatterns = [
    path(
        "<int:pk>", views.RoomDetail.as_view(), name="detail"
    ),  # detail take argument "pk"
    path(
        "search", views.SearchView.as_view(), name="search"
    ),  # we can use name in html.
]

users/urls.py
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path("login", views.LoginView.as_view(), name="login"),
    path("logout", views.log_out, name="logout"),
    path("signup", views.SignUpView.as_view(), name="signup"),
]

templates/partials/footer.html
<footer>&copy; JBnB.</footer>

templates/partials/nav.html
<a href="/">JBnB</a>
<ul>
    {% if user.is_authenticated %}
        <li><a href="{% url "users:logout" %}">Log Out</a></li>
    {% else %}
        <li><a href="{% url "users:login" %}">Log In</a></li>
        <li><a href="{% url "users:signup" %}">Sign Up</a></li>
    {% endif %}
        <li><a href="{% url "rooms:search" %}">Search</a></li>
    
</ul>
   